### ISSUE TITLE
Скройте финальный проекты ЯНДЕКС ПРАКТИКУМА

### ISSUE THREAD

**Issue by bekjon1990** [themasterid/py_blog_django#3]
Прошу Вас скрыть финальные проекты яндекс практикума что бы студенты не могули списывать с ваших проектов

**Comment by themasterid** [comment]
Первое, у всех студентов ЯП финальные проекты идут в резюме как портфелио, вы предлагаете 9 месяцев просто убрать из резюме? Второе, сотни выпускников практикума держат свои репозитории с финальными проектами открытыми, вы им всем написали? Третье, могу я узнать, кто вам давал такое право, и на каком этапе жизни вы вдруг решили, что можете просить людей скрыть какие то репозитории?  В ЯП есть наказание за плагиат, пусть там люди решают, как  с таким поступать. Спасибо за понимание.
